=== ryanzhang5/multi-test/my-test/src/main/java/org/spring/xmlvalidation/order_schema.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="shipOrder" type="order" />
	<xsd:complexType name="shipAddress">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="street" type="xsd:string" />
			<xsd:element name="address" type="xsd:string" />
			<xsd:element name="country" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="cdItem">
		<xsd:sequence>
			<xsd:element name="title" type="xsd:string" />
			<xsd:element name="quantity" type="xsd:positiveInteger" />
			<xsd:element name="price" type="xsd:decimal" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="cdItems">
		<xsd:sequence>
			<xsd:element name="item" type="cdItem" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="order">
		<xsd:sequence>
			<xsd:element name="shipTo" type="shipAddress" />
			<xsd:element name="items" type="cdItems" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== ryanzhang5/multi-test/my-test/src/main/java/org/spring/xmlvalidation/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<shipOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="src/main/java/org/spring/xmlvalidation/order_schema.xsd">
	<shipTo>
		<name>Tove Svendson</name>
		<street>Ragnhildvei 2</street>
		<address>4000 Stavanger</address>
		<country>Norway</country>
	</shipTo>
	<items>
		<item>
			<title>Empire Burlesque</title>
			<quantity>1</quantity>
			<price>10.90</price>
		</item>

	</items>
</shipOrder>
